#!url=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/tool/module/12306.module
#!name=12306去广告
#!desc=过滤12306应用内广告及开屏广告
#!author=RuCu6[https://github.com/RuCu6]
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/12306.png
#!openUrl=https://apps.apple.com/app/id564818797
#!tag=去广告
#!loon_version=3.2.4(787)
#!homepage=https://hub.kelee.one
#!date=2025-05-13 15:17:08

[Rule]
DOMAIN,ad.12306.cn,DIRECT

[Script]
移除12306开屏广告 = type=http-request,script-path=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/JavaScript/12306/12306_remove_splashscreen_ads.js,pattern=^https:\/\/ad\.12306\.cn\/ad\/ser\/getAdList$,requires-body=true

移除12306应用内广告 = type=http-request,script-path=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/JavaScript/12306/12306_remove_ads.js,pattern=^https:\/\/mobile\.12306\.cn\/otsmobile\/app\/mgs\/mgw\.htm$

[MITM]
hostname = %APPEND% ad.12306.cn, mobile.12306.cn
