#!url=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/tool/module/awesun.module
#!url=http://script.hub/file/_start_/https://kelee.one/Tool/Loon/Lpx/OraySunlogin_remove_ads.lpx/_end_/OraySunlogin_remove_ads.sgmodule?type=loon-plugin&target=shadowrocket-module&del=true&jqEnabled=true
#!name=向日葵去广告
#!desc=移除开屏广告、广告横幅。
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/OraySunlogin.png
#!openUrl=https://apps.apple.com/app/id551941458
#!tag=去广告
#!loon_version=3.2.4(787)
#!homepage=https://hub.kelee.one
#!date=2025-05-13 15:17:08

[URL Rewrite]
^https:\/\/client-api-v2\.oray\.com\/materials\/SLCC_iOS_DEVICE_FREE\? - reject-dict

[MITM]
hostname = %APPEND% client-api-v2.oray.com

