#!url=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/tool/module/boxjs.module
#!name=BoxJs
#!desc=http://boxjs.com
#!author=ChavyLeung
#!homepage=https://docs.boxjs.app/
#!icon=https://raw.githubusercontent.com/chavyleung/scripts/master/box/icons/BoxJs.png
#!category=BoxJs

[General]
force-http-engine-hosts = %APPEND% boxjs.com, boxjs.net, *.boxjs.com, *.boxjs.net

[Rule]
DOMAIN-SUFFIX,jsdelivr.net,DIRECT

[Script]
Rewrite: BoxJs = type=http-request,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/box/chavy.boxjs.js,pattern=^https?:\/\/(.+\.)?boxjs\.(com|net),requires-body=true,timeout=120

[MITM]
hostname = %INSERT% boxjs.com, boxjs.net, *.boxjs.com, *.boxjs.net
