#!url=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/tool/module/iringosiri.module
#!name= iRingo: ⭕ Siri
#!desc=iOS 18⬆️ & macOS 15⬆️\n全面自定义「Siri 请求」功能。\n⚠️ 不含自定义「Siri 建议」功能。
#!openUrl=http://boxjs.com/#/app/iRingo.Siri
#!author=VirgilClyne[https://github.com/VirgilClyne]
#!homepage=https://NSRingo.github.io/guide/Siri/siri
#!icon=https://developer.apple.com/assets/elements/icons/siri/siri-128x128.png
#!category= iRingo
#!date=2024-12-24 04:25:06
#!version=4.2.7
#!arguments=国家和地区代码:"US",Siri区域:"zh_CN",区域:"OFF",Siri响应语言修改:"zh_CN",[调试]日志等级:"WARN"

[Script]
⭕ Siri.Search.request = type=http-request,script-path=https://github.com/NSRingo/Siri/releases/download/v4.2.7/request.bundle.js,pattern=^https?:\/\/(api-siri|api2|api-.+)\.smoot\.apple\.com\/search,argument="{"CountryCode":"{{{国家和地区代码}}}","SiriLocale":"{{{Siri区域}}}","Region":"{{{区域}}}","SiriResponseLanguageVariant":"{{{Siri响应语言修改}}}","LogLevel":"{{{[调试]日志等级}}}"}"

⭕ Siri.SiriSearch.request = type=http-request,script-path=https://github.com/NSRingo/Siri/releases/download/v4.2.7/request.bundle.js,pattern=^https?:\/\/(guzzoni|api2|api-.+)\.smoot\.apple\.com\/apple\.parsec\.siri\.v2alpha\.SiriSearch\/SiriSearch,requires-body=true,binary-body-mode=true,argument="{"CountryCode":"{{{国家和地区代码}}}","SiriLocale":"{{{Siri区域}}}","Region":"{{{区域}}}","SiriResponseLanguageVariant":"{{{Siri响应语言修改}}}","LogLevel":"{{{[调试]日志等级}}}"}"

🔍 Safari.SafariSearch.request = type=http-request,script-path=https://github.com/NSRingo/Siri/releases/download/v4.2.7/request.bundle.js,pattern=^https?:\/\/api-safari(-.+)?\.smoot\.apple\.com\/apple\.parsec\.safari\.v1alpha\.SafariSearch\/SafariSearch,requires-body=true,binary-body-mode=true,argument="{"CountryCode":"{{{国家和地区代码}}}","SiriLocale":"{{{Siri区域}}}","Region":"{{{区域}}}","SiriResponseLanguageVariant":"{{{Siri响应语言修改}}}","LogLevel":"{{{[调试]日志等级}}}"}"

🔍 Lookup.LookupSearch.request = type=http-request,script-path=https://github.com/NSRingo/Siri/releases/download/v4.2.7/request.bundle.js,pattern=^https?:\/\/api-lookup(-.+)?\.smoot\.apple\.com\/apple\.parsec\.lookup\.v1alpha\.LookupSearch\/LookupSearch,requires-body=true,binary-body-mode=true,argument="{"CountryCode":"{{{国家和地区代码}}}","SiriLocale":"{{{Siri区域}}}","Region":"{{{区域}}}","SiriResponseLanguageVariant":"{{{Siri响应语言修改}}}","LogLevel":"{{{[调试]日志等级}}}"}"

🔍 Visualsearch.VisualSearch.request = type=http-request,script-path=https://github.com/NSRingo/Siri/releases/download/v4.2.7/request.bundle.js,pattern=^https?:\/\/(api2|api-.+)\.smoot\.apple\.com\/apple\.parsec\.visualsearch\.v2\.VisualSearch\/VisualSearch,requires-body=true,binary-body-mode=true,argument="{"CountryCode":"{{{国家和地区代码}}}","SiriLocale":"{{{Siri区域}}}","Region":"{{{区域}}}","SiriResponseLanguageVariant":"{{{Siri响应语言修改}}}","LogLevel":"{{{[调试]日志等级}}}"}"

🔍 ResponseFramework.Engagement.EngagementSearch.request = type=http-request,script-path=https://github.com/NSRingo/Siri/releases/download/v4.2.7/request.bundle.js,pattern=^https?:\/\/(api-.+)\.smoot\.apple\.com\/apple\.parsec\.responseframework\.engagement\.v1alpha\.EngagementSearch\/EngagementSearch,requires-body=true,binary-body-mode=true,argument="{"CountryCode":"{{{国家和地区代码}}}","SiriLocale":"{{{Siri区域}}}","Region":"{{{区域}}}","SiriResponseLanguageVariant":"{{{Siri响应语言修改}}}","LogLevel":"{{{[调试]日志等级}}}"}"

🔍 Spotlight.ZkwSuggestService.request = type=http-request,script-path=https://github.com/NSRingo/Siri/releases/download/v4.2.7/request.bundle.js,pattern=^https?:\/\/(api-.+)\.smoot\.apple\.com\/apple\.parsec\.spotlight\.v1alpha\.ZkwSuggestService\/Suggest,requires-body=true,binary-body-mode=true,argument="{"CountryCode":"{{{国家和地区代码}}}","SiriLocale":"{{{Siri区域}}}","Region":"{{{区域}}}","SiriResponseLanguageVariant":"{{{Siri响应语言修改}}}","LogLevel":"{{{[调试]日志等级}}}"}"

[MITM]
hostname = %APPEND% guzzoni.smoot.apple.com, api2.smoot.apple.com, api-*.smoot.apple.com
