#!url=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/tool/module/iringosearch.module
#!name= iRingo: 🔍 Search
#!desc=iOS 17.6⬇️\n全面自定义「Siri 建议」功能。\n⚠️ 不含自定义「询问 Siri」功能。
#!openUrl=http://boxjs.com/#/app/iRingo.Spotlight
#!author=VirgilClyne[https://github.com/VirgilClyne]
#!homepage=https://NSRingo.github.io/guide/Siri/spotlight
#!icon=https://developer.apple.com/assets/elements/icons/spotlight/spotlight-128x128.png
#!category= iRingo
#!date=2024-12-24 04:25:10
#!version=4.2.7
#!arguments=国家和地区代码:"SG",搜索领域:"web,itunes,app_store,movies,restaurants,maps",功能:"flightutilities,lookup,mail,messages,news,safari,siri,spotlight,visualintelligence",Safari智能历史记录:true,[调试]日志等级:"WARN"

[Script]
🔍 Search.Bag.request = type=http-request,script-path=https://github.com/NSRingo/Siri/releases/download/v4.2.7/request.bundle.js,pattern=^https?:\/\/api2?\.smoot\.apple\.(com|cn)\/bag,argument="{"CountryCode":"{{{国家和地区代码}}}","Domains":"{{{搜索领域}}}","Functions":"{{{功能}}}","SafariSmartHistory":{{{Safari智能历史记录}}},"LogLevel":"{{{[调试]日志等级}}}"}"

🔍 Search.Bag.response = type=http-response,script-path=https://github.com/NSRingo/Siri/releases/download/v4.2.7/response.bundle.js,pattern=^https?:\/\/api2?\.smoot\.apple\.(com|cn)\/bag,requires-body=true,argument="{"CountryCode":"{{{国家和地区代码}}}","Domains":"{{{搜索领域}}}","Functions":"{{{功能}}}","SafariSmartHistory":{{{Safari智能历史记录}}},"LogLevel":"{{{[调试]日志等级}}}"}"

🔍 Search.Search.request = type=http-request,script-path=https://github.com/NSRingo/Siri/releases/download/v4.2.7/request.bundle.js,pattern=^https?:\/\/api(2|-.+)\.smoot\.apple\.com\/search,argument="{"CountryCode":"{{{国家和地区代码}}}","Domains":"{{{搜索领域}}}","Functions":"{{{功能}}}","SafariSmartHistory":{{{Safari智能历史记录}}},"LogLevel":"{{{[调试]日志等级}}}"}"

🔍 Search.Flight.request = type=http-request,script-path=https://github.com/NSRingo/Siri/releases/download/v4.2.7/request.bundle.js,pattern=^https?:\/\/api(2|-.+)\.smoot\.apple\.com\/flight,argument="{"CountryCode":"{{{国家和地区代码}}}","Domains":"{{{搜索领域}}}","Functions":"{{{功能}}}","SafariSmartHistory":{{{Safari智能历史记录}}},"LogLevel":"{{{[调试]日志等级}}}"}"

[MITM]
hostname = %APPEND% api*.smoot.apple.com, api.smoot.apple.cn
