#!name=起点读书签到
#!desc=支持多账号对于"起点读书App"的签到功能，默认仅签到，其他任务需手动开启开关。
#!icon=https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/97/40/5e/97405e49-87bb-3f0a-bf3a-91cf8fdf99a0/AppIcon-0-0-1x_U007epad-0-1-0-0-sRGB-GLES2_U002c0-85-220.png/144x144.png
#!arguments-desc=- 是否开启抓取重写: ["起点读书","#"] \n\n- 是否开启调试模式: ["true","false"]\n\n - 激励任务: ["true","false"]\n\n- 每日任务: ["true","false"]\n\n- 每日抽奖: ["true","false"]\n\n- 每周兑换: ["true","false"]\n\n- 章节卡片: ["true","false"]\n\n- 大咖荐书: ["true","false"]
#!arguments=是否开启抓取重写:true,是否开启调试模式:false,激励任务:false,每日任务:false,每日抽奖:false,每周兑换:false,章节卡片:false,大咖荐书:false

[Script]
起点读书获取Cookie = type=http-response,script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Tasks/QDReader/qdreader.js,pattern=^https?:\/\/h5\.if\.qidian\.com\/argus\/api\/v1\/user\/getlogininfo,requires-body=true,argument="{{"CAPTURE_ENABLE":{{{是否开启抓取重写}}}},{"QDREADER_DEBUG":{{{是否开启调试模式}}}}}"

起点读书自动签到 = type=cron,cronexp="* 11 02 * * ?",script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Tasks/QDReader/qdreader.js,timeout=60,argument="{{"QDREADER_DEBUG":{{{是否开启调试模式}}}},{"QDREADER_ADV_JOB_ENABLE":{{{激励任务}}}},{"QDREADER_EXTRA_ADV_JOB_ENABLE":{{{每日任务}}}},{"QDREADER_LOTTERY_ENABLE":{{{每日抽奖}}}},{"QDREADER_WEEKLY_EXCHANGE_ENABLE":{{{每周兑换}}}},{"QDREADER_CHAPTER_CARD_ENABLE":{{{章节卡片}}}},{"QDREADER_MESSAGE_BOX_ENABLE":{{{大咖荐书}}}}"

[MITM]
hostname = %APPEND% h5.if.qidian.com
