#!url=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/tool/module/scripthub.module
#!name=Script Hub
#!desc=https://script.hub
#!author=@小白脸 @xream @keywos @ckyb
#!homepage=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/modules/script-hub.rocket.module

[General]
force-http-engine-hosts = %APPEND% script.hub, *.script.hub

[Script]
Script Hub: 前端 = type=http-request,script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/script-hub.js,pattern=^https?:\/\/script\.hub\/($|edit\/|reload),timeout=300

Script Hub: 重写转换 = type=http-request,script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/Rewrite-Parser.js,pattern=^https?:\/\/script\.hub\/file\/_start_\/.+type=(?:qx-rewrite|surge-module|loon-plugin|all-module), timeout=300

Script Hub: 规则集转换 = type=http-request,script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/rule-parser.js,pattern=^https?:\/\/script\.hub\/file\/_start_\/.+type=rule-set,timeout=300

Script Hub: 脚本转换 = type=http-request,script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/script-converter.js,pattern=^https?:\/\/script\.hub\/convert\/,timeout=300

[MITM]
hostname = %APPEND% script.hub, *.script.hub