#!url=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/tool/module/spotifydualsubs.module
#!name=🍿️ DualSubs: 🎵 Spotify
#!desc=Spotify 增强及双语歌词
#!openUrl=http://boxjs.com/#/app/DualSubs.Spotify
#!author=VirgilClyne[https://github.com/VirgilClyne]
#!homepage=https://DualSubs.github.io/guide/spotify
#!icon=https://github.com/DualSubs/Spotify/raw/main/src/assets/icon_rounded.png
#!category=🍿️ DualSubs
#!date=2025-10-25 04:40:57
#!version=1.9.12
#!arguments=[歌词]启用类型(多选):Translate,[翻译器]主语言(源语言):AUTO,[翻译器]副语言(目标语言):ZH,[翻译器]服务商API:Google,[歌词]服务商API:NeteaseMusic,[调试]日志等级:WARN

[Script]
🍿️ DualSubs.Spotify.Tracks.response.json = type=http-response,script-path=https://github.com/DualSubs/Spotify/releases/download/v1.9.12/response.bundle.js,pattern=^https?:\/\/api\.spotify\.com\/v1\/tracks\?,argument="{"Types":"{{{[歌词]启用类型(多选)}}}","Languages[0]":"{{{[翻译器]主语言(源语言)}}}","Languages[1]":"{{{[翻译器]副语言(目标语言)}}}","Vendor":"{{{[翻译器]服务商API}}}","LrcVendor":"{{{[歌词]服务商API}}}","LogLevel":"{{{[调试]日志等级}}}"}"

🍿️ DualSubs.Spotify.Lyrics.request.json = type=http-request,script-path=https://github.com/DualSubs/Spotify/releases/download/v1.9.12/request.bundle.js,pattern=^https?:\/\/(.+-spclient|spclient\.wg).spotify\.com(:443)?\/color-lyrics\/v2\/track\/(.+)\?(.*)format=json,requires-body=true,argument="{"Types":"{{{[歌词]启用类型(多选)}}}","Languages[0]":"{{{[翻译器]主语言(源语言)}}}","Languages[1]":"{{{[翻译器]副语言(目标语言)}}}","Vendor":"{{{[翻译器]服务商API}}}","LrcVendor":"{{{[歌词]服务商API}}}","LogLevel":"{{{[调试]日志等级}}}"}"

🍿️ DualSubs.Spotify.Lyrics.request.proto = type=http-request,script-path=https://github.com/DualSubs/Spotify/releases/download/v1.9.12/request.bundle.js,pattern=^https?:\/\/(.+-spclient|spclient\.wg).spotify\.com(:443)?\/color-lyrics\/v2\/track\/\w+\?(.*),requires-body=true,binary-body-mode=true,argument="{"Types":"{{{[歌词]启用类型(多选)}}}","Languages[0]":"{{{[翻译器]主语言(源语言)}}}","Languages[1]":"{{{[翻译器]副语言(目标语言)}}}","Vendor":"{{{[翻译器]服务商API}}}","LrcVendor":"{{{[歌词]服务商API}}}","LogLevel":"{{{[调试]日志等级}}}"}"

🍿️ DualSubs.Spotify.Translate.Lyrics.response.json = type=http-response,script-path=https://github.com/DualSubs/Universal/releases/latest/download/Translate.response.bundle.js,pattern=^https?:\/\/(.+-spclient|spclient\.wg).spotify\.com(:443)?\/color-lyrics\/v2\/track\/(.+)\?(.*)format=json(.*)subtype=Translate,requires-body=true,argument="{"Types":"{{{[歌词]启用类型(多选)}}}","Languages[0]":"{{{[翻译器]主语言(源语言)}}}","Languages[1]":"{{{[翻译器]副语言(目标语言)}}}","Vendor":"{{{[翻译器]服务商API}}}","LrcVendor":"{{{[歌词]服务商API}}}","LogLevel":"{{{[调试]日志等级}}}"}"

🍿️ DualSubs.Spotify.Translate.Lyrics.response.proto = type=http-response,script-path=https://github.com/DualSubs/Universal/releases/latest/download/Translate.response.bundle.js,pattern=^https?:\/\/(.+-spclient|spclient\.wg).spotify\.com(:443)?\/color-lyrics\/v2\/track\/\w+\?(.*)subtype=Translate,requires-body=true,binary-body-mode=true,argument="{"Types":"{{{[歌词]启用类型(多选)}}}","Languages[0]":"{{{[翻译器]主语言(源语言)}}}","Languages[1]":"{{{[翻译器]副语言(目标语言)}}}","Vendor":"{{{[翻译器]服务商API}}}","LrcVendor":"{{{[歌词]服务商API}}}","LogLevel":"{{{[调试]日志等级}}}"}"

🍿️ DualSubs.Spotify.External.Lyrics.response.json = type=http-response,script-path=https://github.com/DualSubs/Universal/releases/latest/download/External.Lyrics.response.bundle.js,pattern=^https?:\/\/(.+-spclient|spclient\.wg).spotify\.com(:443)?\/color-lyrics\/v2\/track\/(.+)\?(.*)format=json(.*)subtype=External,requires-body=true,argument="{"Types":"{{{[歌词]启用类型(多选)}}}","Languages[0]":"{{{[翻译器]主语言(源语言)}}}","Languages[1]":"{{{[翻译器]副语言(目标语言)}}}","Vendor":"{{{[翻译器]服务商API}}}","LrcVendor":"{{{[歌词]服务商API}}}","LogLevel":"{{{[调试]日志等级}}}"}"

🍿️ DualSubs.Spotify.External.Lyrics.response.proto = type=http-response,script-path=https://github.com/DualSubs/Universal/releases/latest/download/External.Lyrics.response.bundle.js,pattern=^https?:\/\/(.+-spclient|spclient\.wg).spotify\.com(:443)?\/color-lyrics\/v2\/track\/\w+\?(.*)subtype=External,requires-body=true,binary-body-mode=true,argument="{"Types":"{{{[歌词]启用类型(多选)}}}","Languages[0]":"{{{[翻译器]主语言(源语言)}}}","Languages[1]":"{{{[翻译器]副语言(目标语言)}}}","Vendor":"{{{[翻译器]服务商API}}}","LrcVendor":"{{{[歌词]服务商API}}}","LogLevel":"{{{[调试]日志等级}}}"}"

[MITM]
hostname = %APPEND% api.spotify.com, spclient.wg.spotify.com, *-spclient.spotify.com