#!url=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/tool/module/testflight.module
#!name=自动加入TestFlight
#!desc=自动监控TestFlight名额，一旦有新的名额即刻加入。
#!author=奶思[https://github.com/fmz200], DecoAri[https://github.com/DecoAri], xream[https://github.com/xream]
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/TestFlight.png
#!openUrl=https://apps.apple.com/app/id899247664
#!tag=定时任务
#!loon_version=3.4.0(962)
#!homepage=https://hub.kelee.one
#!date=2026-06-01 17:11:35
#!arguments=捕获账号令牌:false,自动加入TF:false,监控TF位置:true,加入TF定时参数:"0 0/2 * * * ?",监控TF定时参数:"0 * * * * ?"

[Rule]
DOMAIN,testflight.apple.com,DIRECT

[Script]
获取账号令牌 = type=http-request,script-path=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/JavaScript/TestFlight/CaptureAccountToken.js,pattern=^https?:\/\/testflight\.apple\.com\/v3\/accounts\/.*\/apps$,argument="{"CaptureAccountToken":{{{捕获账号令牌}}}}"


自动加入TF = type=cron,cronexp="{"TaskCron":"{{{加入TF定时参数}}}"}",script-path=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/JavaScript/TestFlight/AutoJoinTF.js,timeout=600,argument="{"RunTask":{{{自动加入TF}}},"RunMonitor":{{{监控TF位置}}}}"


监控TF位置 = type=cron, cronexp="{"TaskMonitor":"{{{监控TF定时参数}}}"}",script-path=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/JavaScript/TestFlight/AutoMonitorTF.js,timeout=30
