#!url=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/tool/module/youdaodic.module
#!name=网易有道词典去广告
#!desc=移除开屏广告、弹窗广告、横幅广告、信息流广告、旧版翻译页面广告及搜索填充词。
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/YoudaoDict.png
#!openUrl=https://apps.apple.com/app/id353115739
#!tag=去广告
#!loon_version=3.2.4(787)
#!homepage=https://hub.kelee.one
#!date=2025-05-13 15:17:08

[URL Rewrite]
^https:\/\/gorgon\.youdao\.com\/gorgon\/brand\/prefetch\.s\? - reject-dict
^https:\/\/gorgon\.youdao\.com\/gorgon\/request\.s\? - reject-dict

[MITM]
hostname = %APPEND% gorgon.youdao.com, dict.youdao.com

