#!name=🍿️ DualSubs: ▶️ YouTube
#!desc=YouTube 增强及双语字幕(歌词)
#!openUrl=http://boxjs.com/#/app/DualSubs.YouTube
#!author=VirgilClyne[https://github.com/VirgilClyne]
#!homepage=https://DualSubs.github.io/guide/youtube
#!icon=https://github.com/DualSubs/YouTube/raw/main/src/assets/icon_rounded.png
#!category=🍿️ DualSubs
#!date=2024-12-11 01:41:21
#!version=1.5.11
#!arguments=[字幕]启用类型:"Official",[歌词]启用类型:"Translate",[字幕]自动显示:true,[字幕]主语言(源语言)字幕位置:"Forward",[翻译器]服务商API:"Google",[翻译器]只显示"自动翻译"字幕:false,调试日志等级:"WARN"

[Rule]
URL-REGEX,^https?:\/\/([\w-]+)\.googlevideo\.com\/initplayback(\?.*oad=.+)$,REJECT-TINYGIF

[Script]
# YouTube
🍿️ DualSubs.YouTube.Player.request.json = type=http-request,script-path=https://github.com/DualSubs/YouTube/releases/download/v1.5.11/request.bundle.js,pattern=^https?:\/\/(www|m|tv)\.youtube\.com\/youtubei\/v1\/player(\?.+)?$, requires-body=true,argument="{"Type":"{{{[字幕]启用类型}}}","Type":"{{{[歌词]启用类型}}}","AutoCC":{{{[字幕]自动显示}}},"Position":"{{{[字幕]主语言(源语言)字幕位置}}}","Vendor":"{{{[翻译器]服务商API}}}","ShowOnly":{{{[翻译器]只显示"自动翻译"字幕}}},"LogLevel":"{{{调试日志等级}}}"}"

🍿️ DualSubs.YouTube.Player.response.json = type=http-response,script-path=https://github.com/DualSubs/YouTube/releases/download/v1.5.11/response.bundle.js,pattern=^https?:\/\/(www|m|tv)\.youtube\.com\/youtubei\/v1\/player(\?.+)?$,requires-body=true,argument="{"Type":"{{{[字幕]启用类型}}}","Type":"{{{[歌词]启用类型}}}","AutoCC":{{{[字幕]自动显示}}},"Position":"{{{[字幕]主语言(源语言)字幕位置}}}","Vendor":"{{{[翻译器]服务商API}}}","ShowOnly":{{{[翻译器]只显示"自动翻译"字幕}}},"LogLevel":"{{{调试日志等级}}}"}"

🍿️ DualSubs.YouTube.Player.request.proto = type=http-request,script-path=https://github.com/DualSubs/YouTube/releases/download/v1.5.11/request.bundle.js,pattern=^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/player(\?.+)?$,requires-body=true,binary-body-mode=true,argument="{"Type":"{{{[字幕]启用类型}}}","Type":"{{{[歌词]启用类型}}}","AutoCC":{{{[字幕]自动显示}}},"Position":"{{{[字幕]主语言(源语言)字幕位置}}}","Vendor":"{{{[翻译器]服务商API}}}","ShowOnly":{{{[翻译器]只显示"自动翻译"字幕}}},"LogLevel":"{{{调试日志等级}}}"}"

🍿️ DualSubs.YouTube.Player.response.proto = type=http-response,script-path=https://github.com/DualSubs/YouTube/releases/download/v1.5.11/response.bundle.js,pattern=^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/player(\?.+)?$,requires-body=true,binary-body-mode=true,argument="{"Type":"{{{[字幕]启用类型}}}","Type":"{{{[歌词]启用类型}}}","AutoCC":{{{[字幕]自动显示}}},"Position":"{{{[字幕]主语言(源语言)字幕位置}}}","Vendor":"{{{[翻译器]服务商API}}}","ShowOnly":{{{[翻译器]只显示"自动翻译"字幕}}},"LogLevel":"{{{调试日志等级}}}"}"

🍿️ DualSubs.YouTube.GetWatch.response.proto = type=http-response,script-path=https://github.com/DualSubs/YouTube/releases/download/v1.5.11/response.bundle.js,pattern=^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/get_watch(\?.+)?$,requires-body=true,binary-body-mode=true,argument="{"Type":"{{{[字幕]启用类型}}}","Type":"{{{[歌词]启用类型}}}","AutoCC":{{{[字幕]自动显示}}},"Position":"{{{[字幕]主语言(源语言)字幕位置}}}","Vendor":"{{{[翻译器]服务商API}}}","ShowOnly":{{{[翻译器]只显示"自动翻译"字幕}}},"LogLevel":"{{{调试日志等级}}}"}"

🍿️ DualSubs.YouTube.TimedText.request = type=http-request,script-path=https://github.com/DualSubs/YouTube/releases/download/v1.5.11/request.bundle.js,pattern=^https?:\/\/(www|m)\.youtube\.com\/api\/timedtext(\?.+)?$,argument="{"Type":"{{{[字幕]启用类型}}}","Type":"{{{[歌词]启用类型}}}","AutoCC":{{{[字幕]自动显示}}},"Position":"{{{[字幕]主语言(源语言)字幕位置}}}","Vendor":"{{{[翻译器]服务商API}}}","ShowOnly":{{{[翻译器]只显示"自动翻译"字幕}}},"LogLevel":"{{{调试日志等级}}}"}"

🍿️ DualSubs.YouTube.Composite.TimedText.response = type=http-response,script-path=https://github.com/DualSubs/Universal/releases/latest/download/Composite.Subtitles.response.bundle.js,pattern=^https?:\/\/(www|m)\.youtube\.com\/api\/timedtext\?(.*)subtype=(Official|External),requires-body=true,argument="{"Type":"{{{[字幕]启用类型}}}","Type":"{{{[歌词]启用类型}}}","AutoCC":{{{[字幕]自动显示}}},"Position":"{{{[字幕]主语言(源语言)字幕位置}}}","Vendor":"{{{[翻译器]服务商API}}}","ShowOnly":{{{[翻译器]只显示"自动翻译"字幕}}},"LogLevel":"{{{调试日志等级}}}"}"

🍿️ DualSubs.YouTube.Translate.TimedText.response = type=http-response,script-path=https://github.com/DualSubs/Universal/releases/latest/download/Translate.response.bundle.js,pattern=^https?:\/\/(www|m)\.youtube\.com\/api\/timedtext\?(.*)subtype=Translate,requires-body=true,argument="{"Type":"{{{[字幕]启用类型}}}","Type":"{{{[歌词]启用类型}}}","AutoCC":{{{[字幕]自动显示}}},"Position":"{{{[字幕]主语言(源语言)字幕位置}}}","Vendor":"{{{[翻译器]服务商API}}}","ShowOnly":{{{[翻译器]只显示"自动翻译"字幕}}},"LogLevel":"{{{调试日志等级}}}"}"

# YouTube Music
🍿️ DualSubs.YouTubeMusic.Browse.request.json = type=http-request,script-path=https://github.com/DualSubs/YouTube/releases/download/v1.5.11/request.bundle.js,pattern=^https?:\/\/music\.youtube\.com\/youtubei\/v1\/browse(\?.+)?$,requires-body=true,argument="{"Type":"{{{[字幕]启用类型}}}","Type":"{{{[歌词]启用类型}}}","AutoCC":{{{[字幕]自动显示}}},"Position":"{{{[字幕]主语言(源语言)字幕位置}}}","Vendor":"{{{[翻译器]服务商API}}}","ShowOnly":{{{[翻译器]只显示"自动翻译"字幕}}},"LogLevel":"{{{调试日志等级}}}"}"

🍿️ DualSubs.YouTube.Browse.request.proto = type=http-request,script-path=https://github.com/DualSubs/YouTube/releases/download/v1.5.11/request.bundle.js,pattern=^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/browse(\?.+)?$,requires-body=true,binary-body-mode=true,argument="{"Type":"{{{[字幕]启用类型}}}","Type":"{{{[歌词]启用类型}}}","AutoCC":{{{[字幕]自动显示}}},"Position":"{{{[字幕]主语言(源语言)字幕位置}}}","Vendor":"{{{[翻译器]服务商API}}}","ShowOnly":{{{[翻译器]只显示"自动翻译"字幕}}},"LogLevel":"{{{调试日志等级}}}"}"

🍿️ DualSubs.YouTubeMusic.Translate.Lyrics.response.json = type=http-response,script-path=https://github.com/DualSubs/Universal/releases/latest/download/Translate.response.bundle.js,pattern=^https?:\/\/music\.youtube\.com\/youtubei\/v1\/browse\?(.*)subtype=Translate,requires-body=true,argument="{"Type":"{{{[字幕]启用类型}}}","Type":"{{{[歌词]启用类型}}}","AutoCC":{{{[字幕]自动显示}}},"Position":"{{{[字幕]主语言(源语言)字幕位置}}}","Vendor":"{{{[翻译器]服务商API}}}","ShowOnly":{{{[翻译器]只显示"自动翻译"字幕}}},"LogLevel":"{{{调试日志等级}}}"}"

🍿️ DualSubs.YouTubeMusic.Translate.Lyrics.response.proto = type=http-response,script-path=https://github.com/DualSubs/Universal/releases/latest/download/Translate.response.bundle.js,pattern=^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/browse\?(.*)subtype=Translate,requires-body=true,binary-body-mode=true,argument="{"Type":"{{{[字幕]启用类型}}}","Type":"{{{[歌词]启用类型}}}","AutoCC":{{{[字幕]自动显示}}},"Position":"{{{[字幕]主语言(源语言)字幕位置}}}","Vendor":"{{{[翻译器]服务商API}}}","ShowOnly":{{{[翻译器]只显示"自动翻译"字幕}}},"LogLevel":"{{{调试日志等级}}}"}"

[MITM]
hostname = %APPEND% www.youtube.com, m.youtube.com, tv.youtube.com, music.youtube.com, youtubei.googleapis.com, -redirector*.googlevideo.com, *.googlevideo.com
