#!url=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/tool/shadowrocket/baidumap.module
#!name=百度地图去广告
#!desc=移除开屏广告、出行页面推广、周边页面推广、打车页面推广，精简我的页面。此插件需要IPA签名方可使用，App Store用户请勿使用此插件，务必点击下方主页链接查看详细教程。
#!author=可莉🅥[https://getupnote.com/share/notes/zSn1ShBmzNYISKcTgjXE5oHMrNf2/34bf3aad-7872-497d-b239-198e27e8c84c]
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/BaiduMap.png
#!openUrl=https://apps.apple.com/app/id452186370
#!tag=去广告
#!loon_version=3.2.4(787)
#!homepage=https://getupnote.com/share/notes/zSn1ShBmzNYISKcTgjXE5oHMrNf2/34bf3aad-7872-497d-b239-198e27e8c84c
#!date=2025-05-13 15:17:08

[URL Rewrite]
^https:\/\/afd\.baidu\.com\/afd\/entry\?action=(update|query) - reject-dict
^https:\/\/yongche\.baidu\.com\/gomarketing\/api\/popup\/getentrancecordovaurl$ - reject-dict
^https:\/\/yongche\.baidu\.com\/goorder\/passenger\/cobuild\/pull\? - reject-dict
^https:\/\/yongche\.baidu\.com\/goorder\/passenger\/operationgirdle$ - reject-dict
^https:\/\/yongche\.baidu\.com\/goorder\/passenger\/baseinfo$ - reject-dict
^https:\/\/ecom\.map\.baidu\.com\/ad-ops\/afd\/popup\? - reject-dict
^https:\/\/maphotel\.baidu\.com\/hotel\/goextranet\/activity\/detail\? - reject-dict

[MITM]
hostname = %APPEND% afd.baidu.com, newclient.map.baidu.com, yongche.baidu.com, ecom.map.baidu.com