#!url=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/tool/shadowrocket/douyu.module
#!name=斗鱼去广告
#!desc=移除开屏、首页视频流、首页轮播图广告，移除直播间悬浮窗。
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/Douyu.png
#!openUrl=https://apps.apple.com/app/id863882795
#!tag=去广告
#!loon_version=3.2.4(787)
#!homepage=https://hub.kelee.one
#!date=2025-05-13 15:17:08

[Rule]
URL-REGEX,"^http:\/\/linkmicschedule\.douyucdn\.cn\/im_schedule\/im_gate_list",REJECT
#AND,((DEST-PORT,18000),(PROTOCOL,STUN)),REJECT
AND,((DEST-PORT,18000),(AND,((PROTOCOL,UDP),(OR,((DST-PORT,3478),(DST-PORT,3479),(DST-PORT,19302),(DST-PORT,19305))))
)),REJECT
DOMAIN,stun1.douyucdn.cn,REJECT
DOMAIN,stun1.qvb.qcloud.com,REJECT

[URL Rewrite]
^(http:\/\/)((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/(hlsh5p1\.douyucdn2\.cn)(.*) $1$5$6 307
^https:\/\/rtbapi\.douyucdn\.cn\/japi\/sign\/app\/getinfo - reject-dict

[Script]
移除首页轮播图和视频流广告 = type=http-response,script-path=https://raw.githubusercontent.com/YorkJulian49/dtYF27mKWg01bEuZI3Pxne6HXTN58pvj/refs/heads/main/JavaScript/Douyu/Douyu_remove_ads.js,pattern=^https:\/\/apiv2\.douyucdn\.cn\/mgapi\/livenc\/home\/getRecV3,requires-body=true

[MITM]
hostname = %APPEND% rtbapi.douyucdn.cn, apiv2.douyucdn.cn, venus.douyucdn.cn